#!/bin/bash

#PBS -l select=1:ncpus=16:mem=128gb
#PBS -l walltime=24:00:00
#PBS -N mean_fri_poisson_method
#PBS -M sophie.yang@unsw.edu.au
#PBS -m ae
#PBS -j oe
#PBS -o /home/z5208613/honours/output_report_mean_fri_poisson_method

module purge
module add r/4.3.1
module add geos/3.9.1
module add perl/5.36.0
module add gdal/3.5.3
module add proj/8.2.1
module add sqlite/3.39.4
module add udunits/2.2.28

cd honours

Rscript mean_fri_poisson_method.R