#!/bin/bash

#PBS -l select=1:ncpus=50:mem=128gb
#PBS -l walltime=12:00:00
#PBS -N median_fri_survival_job
#PBS -M sophie.yang@unsw.edu.au
#PBS -m ae
#PBS -j oe
#PBS -o /home/z5208613/honours/output_report_median_fri_survival_analysis_method

module purge
module add r/4.3.1
module add geos/3.9.1
module add perl/5.36.0
module add gdal/3.5.3
module add proj/8.2.1
module add sqlite/3.39.4
module add udunits/2.2.28

cd honours

Rscript median_fri_survival_analysis_method.R